# Generated by Django 6.0.4 on 2026-07-25 18:34

import dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=15)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha_produccion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.producto')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='CampanaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Ej: 20.00 para 20% de descuento', max_digits=5)),
                ('dias_sin_compra', models.PositiveIntegerField(default=30, help_text='Se elige entre clientes que no han comprado este producto en los últimos X días (o nunca lo han comprado).')),
                ('cantidad_clientes', models.PositiveIntegerField(default=10, help_text='Tope preferido de clientes "ganadores" por ejecución. El límite real será el menor entre esto, el stock disponible y el porcentaje_maximo_clientes.')),
                ('porcentaje_maximo_clientes', models.DecimalField(decimal_places=2, default=10, help_text='Tope como % del total de clientes activos que pueden recibir el premio en UNA sola ejecución (ej: 10.00 = máx 10% de la base). Evita saturar de descuentos y controla el consumo de memoria/consultas.', max_digits=5)),
                ('stock_reservado_no_ofertable', models.PositiveIntegerField(default=0, help_text='Unidades de stock que NO se cuentan como disponibles para oferta (colchón extra por encima del stock_minimo del producto).')),
                ('dias_validez_premio', models.PositiveIntegerField(default=7, help_text='Cuántos días dura activo el premio para el cliente que lo ganó')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('UNICA', 'Única vez')], default='SEMANAL', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Apágalo para pausar la campaña sin borrarla')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = sin fecha de fin', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('productos', models.ManyToManyField(help_text='Quesos/productos que se quieren mover', related_name='campanas_descuento', to='dashboard.producto')),
            ],
            options={
                'db_table': 'campana_descuento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='dashboard.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='DescuentoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=dashboard.models.generar_codigo, max_length=10, unique=True)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_con_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('mostrado', models.BooleanField(default=False, help_text='Si ya se le mostró la tarjeta/animación de premio')),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='dashboard.campanadescuento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_ganados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.producto')),
            ],
            options={
                'db_table': 'descuento_asignado',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('campana', 'usuario', 'producto'), name='un_premio_por_cliente_por_campana')],
            },
        ),
    ]
