# Generated by Django 6.0.4 on 2026-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del lote actual (se carga manualmente). Se usa solo como sugerencia visual al armar campañas de descuento.', null=True),
        ),
    ]
