# Generated by Django 6.0.4 on 2026-07-21 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDescuentoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('dias_sin_venderse_min', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_multiplicador_min', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 1.5 = se activa si stock_actual >= stock_minimo * 1.5', max_digits=4, null=True)),
                ('dias_antes_vencimiento_max', models.PositiveIntegerField(blank=True, null=True)),
                ('descuento_porcentaje', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='dashboard.producto')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.regladescuentoautomatico')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
