# Generated by Django 6.0.4 on 2026-08-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_producto_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PerfilEmple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado')], default='cliente', max_length=20)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
