# Generated by Django 6.0.4 on 2026-08-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_perfil_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiradaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_key', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('SIGUE_INTENTANDO', 'Sigue intentando'), ('CUPON_5', 'Cupón 5% próxima compra'), ('ENVIO_GRATIS', 'Envío gratis'), ('BOLETO_DORADO', 'Boleto dorado')], max_length=20)),
                ('reclamado', models.BooleanField(default=False, help_text='Si ya se aplicó el efecto del premio (cupón/envío/boleto).')),
                ('boleto_usado', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiradas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tirada_diaria',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='una_tirada_por_usuario_por_dia'), models.UniqueConstraint(fields=('sesion_key', 'fecha'), name='una_tirada_por_sesion_por_dia')],
            },
        ),
    ]
