# Generated by Django 6.0.4 on 2026-08-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_tiradadiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
