# Generated by Django 6.0.4 on 2026-08-22 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_venta_mp_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('incidencia', models.CharField(blank=True, help_text='Problema reportado en el pedido (retraso, producto dañado, cliente ausente, etc.)', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('repartidor', models.ForeignKey(blank=True, help_text='Empleado encargado de repartir este pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='dashboard.venta')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
