# Generated by Django 6.0.4 on 2026-08-28 02:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produccion',
            options={'ordering': ['-fecha_produccion']},
        ),
        migrations.AddField(
            model_name='produccion',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2099, 12, 31), help_text='Fecha de vencimiento de este lote específico.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='dashboard.producto'),
        ),
    ]
