# Generated by Django 6.0.4 on 2026-08-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_produccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
    ]
