# Generated by Django 6.0.4 on 2026-08-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_producto_imagen_hash_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ruta_polyline',
            field=models.TextField(blank=True, help_text='Ruta codificada que devuelve Directions API, para no recalcularla cada vez', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfilemple',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Si puede recibir nuevas entregas asignadas'),
        ),
        migrations.AddField(
            model_name='perfilemple',
            name='repartidor_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfilemple',
            name='repartidor_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfilemple',
            name='ubicacion_actualizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dashboard.pedido')),
            ],
            options={
                'db_table': 'historial_estado_pedido',
                'ordering': ['fecha'],
            },
        ),
    ]
