# Generated by Django 6.0.4 on 2026-08-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notificado_proximidad',
            field=models.BooleanField(default=False, help_text='Evita mandar la notificación de "está cerca" más de una vez'),
        ),
    ]
