# Generated by Django 6.0.4 on 2026-08-31 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_pedido_notificado_proximidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioRuletaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ENVIO_GRATIS', 'Envío gratis'), ('BOLETO_DORADO', 'Boleto dorado')], max_length=20, unique=True)),
                ('peso', models.PositiveSmallIntegerField(default=10, help_text='Peso relativo en el sorteo diario (mismo estilo que el % de las campañas).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True, help_text='Apágalo para sacarlo del sorteo de hoy en adelante, sin perder la configuración.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'premio_ruleta_diaria',
                'ordering': ['codigo'],
            },
        ),
    ]
