# Generated by Django 6.0.4 on 2026-09-03 04:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_configuracionseguridad_sesionactiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanadescuento',
            name='cantidad_clientes',
            field=models.PositiveIntegerField(default=10, help_text='Tope preferido de clientes "ganadores" por ejecución. El límite real será el menor entre esto, el stock disponible y el porcentaje_maximo_clientes.', validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='campanadescuento',
            name='dias_sin_compra',
            field=models.PositiveIntegerField(default=30, help_text='Se elige entre clientes que no han comprado este producto en los últimos X días (o nunca lo han comprado).', validators=[django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AlterField(
            model_name='campanadescuento',
            name='dias_validez_premio',
            field=models.PositiveIntegerField(default=7, help_text='Cuántos días dura activo el premio para el cliente que lo ganó', validators=[django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='campanadescuento',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, help_text='Ej: 20.00 para 20% de descuento', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='campanadescuento',
            name='porcentaje_maximo_clientes',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Tope como % del total de clientes activos que pueden recibir el premio en UNA sola ejecución (ej: 10.00 = máx 10% de la base). Evita saturar de descuentos y controla el consumo de memoria/consultas.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='campanadescuento',
            name='stock_reservado_no_ofertable',
            field=models.PositiveIntegerField(default=0, help_text='Unidades de stock que NO se cuentan como disponibles para oferta (colchón extra por encima del stock_minimo del producto).', validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='configuracionseguridad',
            name='minutos_inactividad',
            field=models.PositiveIntegerField(default=15, help_text='Minutos de inactividad antes de cerrar la sesión automáticamente.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='cantidad_producida',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, default=15, null=True, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
