# Generated by Django 6.0.4 on 2026-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_campanadescuento_cantidad_clientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
