# Generated by Django 6.0.4 on 2026-09-04 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_campanadescuento_cantidad_clientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_preparacion', models.PositiveIntegerField(default=20, help_text='Minutos que tarda la preparación de un pedido antes de salir a ruta.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_entrega',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='minutos_extra_incidencia',
            field=models.PositiveIntegerField(default=0, help_text='Demora extra por la incidencia. Se suma al tiempo estimado que ve el cliente.'),
        ),
    ]
