# Generated by Django 6.0.4 on 2026-09-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_configuracionentrega_pedido_minutos_extra_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_entrega',
            field=models.CharField(blank=True, help_text='PIN de 4 dígitos que el cliente muestra y el repartidor escribe para confirmar que entregó el pedido correcto.', max_length=4, null=True),
        ),
    ]
