# Generated by Django 6.0.4 on 2026-09-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_perfil_telefono'),
        ('dashboard', '0020_pedido_codigo_entrega'),
    ]

    operations = [
    ]
