# Generated by Django 6.0.4 on 2026-09-05 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tiempo_preparacion', 'Tiempo de preparación'), ('minutos_parada', 'Minutos por parada'), ('faltan_repartidores', 'Faltan repartidores')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicada', 'Aplicada'), ('descartada', 'Descartada')], default='pendiente', max_length=15)),
                ('mensaje', models.CharField(max_length=255)),
                ('valor_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_sugerido', models.PositiveIntegerField(blank=True, help_text='Valor que el sistema recomienda. Nulo en sugerencias que no se aplican con un número (ej. "faltan repartidores").', null=True)),
                ('muestras', models.PositiveIntegerField(default=0, help_text='Cuántos pedidos anteriores se miraron para sacar esta conclusión.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sugerencia_sistema',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.AddField(
            model_name='configuracionentrega',
            name='max_pedidos_por_repartidor',
            field=models.PositiveIntegerField(default=3, help_text='Cuántas entregas puede llevar encima un repartidor a la vez. Los pedidos que no entran esperan en la cola (estado pendiente).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='configuracionentrega',
            name='minutos_por_parada',
            field=models.PositiveIntegerField(default=8, help_text='Lo que tarda el repartidor en cada entrega (estacionar, entregar, cobrar). Se suma al tiempo estimado por cada pedido que va antes en la ruta.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden_en_ruta',
            field=models.PositiveIntegerField(blank=True, help_text='Puesto de este pedido dentro de la ruta del repartidor (1 = la próxima parada). Es lo que le permite al cliente ver cuántas entregas van antes de la suya.', null=True),
        ),
    ]
