# Generated by Django 6.0.4 on 2026-09-05 19:23

import django.core.validators
from django.db import migrations, models


def apagar_repartidores(apps, schema_editor):
    """Deja a todos los repartidores fuera de turno.

    El default cambió a False, pero eso solo aplica a filas nuevas: los
    repartidores que ya existían quedarían marcados disponibles sin haber
    activado nada, que es justo lo que se quiso eliminar. Cada uno vuelve
    a aparecer apenas le da a "Empezar a repartir".
    """
    apps.get_model('dashboard', 'PerfilEmple').objects.update(disponible=False)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_sugerenciasistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilemple',
            name='capacidad_productos',
            field=models.PositiveIntegerField(default=20, help_text='Cuántas unidades de producto le caben en el vehículo. El sistema no le asigna entregas que no le quepan.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='perfilemple',
            name='vehiculo',
            field=models.CharField(choices=[('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('carro', 'Carro'), ('a_pie', 'A pie')], default='moto', help_text='En qué reparte. Define cuánto puede cargar de una salida.', max_length=15),
        ),
        migrations.AlterField(
            model_name='perfilemple',
            name='disponible',
            field=models.BooleanField(default=False, help_text='Lo enciende el propio repartidor al empezar su turno. Solo los disponibles reciben entregas.'),
        ),
        migrations.RunPython(apagar_repartidores, migrations.RunPython.noop),
    ]
