# Generated by Django 6.0.4 on 2026-09-06 01:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_perfilemple_capacidad_productos_perfilemple_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ventas', 'Ingresos por ventas'), ('produccion', 'Unidades producidas'), ('clientes', 'Clientes nuevos'), ('pedidos', 'Pedidos entregados')], max_length=15)),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual')], default='mensual', max_length=10)),
                ('estado', models.CharField(choices=[('propuesta', 'Propuesta'), ('activa', 'Activa'), ('cumplida', 'Cumplida'), ('descartada', 'Descartada')], default='propuesta', max_length=12)),
                ('objetivo', models.DecimalField(decimal_places=2, help_text='Cuánto hay que alcanzar en el período.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('base_historica', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio real de los períodos anteriores sobre el que se calculó.', max_digits=12, null=True)),
                ('periodos_analizados', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meta_negocio',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['propuesta', 'activa'])), fields=('tipo', 'fecha_inicio', 'fecha_fin'), name='meta_unica_viva_por_tipo_y_periodo')],
            },
        ),
    ]
